### ISSUE TITLE
Mention that you can put the unknown_morphs field on the back side

### ISSUE THREAD

**Issue by Vilhelm-Ian** [mortii/anki-morphs#84]
## What is the current documentation?

It dosen't mention  you can do it. I have been thinking for some time about this. But always thought not to bother because of the triviality.

## What changes do you suggest?

To avoid  using the highlight feature and simply find out which words are unknown on the card, consider adding the "Unknown words field" to the back of the card template, as shown: {{Unknowns}}.

![image](https://github.com/mortii/anki-morphs/assets/81630959/687ad4a6-1c11-4f60-9864-729b34463d80)

**Comment by HQYang1979** [comment]
Yes, basically I only want the Unknown highlighted. There is no need to highlight learning or more. 

I think this alternative suffices.

**Comment by mortii** [comment]
@Vilhelm-Ian Where in the docs do you want this to be mentioned?

@HQYang1979 instead of using all of these:
``` css
[morph-status=unknown] { background-color: #ffff99; } /* yellow */
[morph-status=learning] { background-color: #f2f2f2; } /* gray */
[morph-status=known] { background-color: #b3e6cc; } /* green */
```
You can just use the unknown part and remove the others:
``` css
[morph-status=unknown] { background-color: #ffff99; } /* yellow */
```

**Comment by HQYang1979** [comment]
> You can just use the unknown part and remove the others: [morph-status=unknown] { color: #f75464; } /* red */

Thank you. Yes I have been doing this.

**Comment by Vilhelm-Ian** [comment]
@mortii Maybe put it here 
![image](https://github.com/mortii/anki-morphs/assets/81630959/a93d2bc9-ddd2-43a7-b27b-a329d7d33756)
It can help people not foot gun themselves

**Comment by mortii** [comment]
> It can help people not foot gun themselves

:rofl: 

Sure, i can add that.

**Comment by HQYang1979** [comment]
![image](https://github.com/mortii/anki-morphs/assets/74698160/ee203744-fec4-4427-a88c-5e3867dfe8ec)

Putting the Focus here is nice. Thank you again. @Vilhelm-Ian

**Comment by mortii** [comment]
@Vilhelm-Ian 'Unknowns' is also and extra field so there is still the same foot shooting potential by using that instead... the only difference between the approaches is that the user does not have to set the css:
``` css
[morph-status=unknown] { color: #f75464; } /* red */
[morph-status=learning] { color: #8bb33d; } /* light-green */
[morph-status=known] { color: green; }
```
I'm not quite sure of the best way to convey this information. Maybe we should create a separate page for 'unknowns' to explain that too? I dunno.
